default:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

stages:
  - infra
  - deploy

infra_job:
  stage: infra
  before_script:
    - cd infra/terraform
  script:
    - echo $(pwd)
    - gitlab-terraform init
    - gitlab-terraform plan
    - |
      if [ $? -eq 0 ]; then 
        gitlab-terraform apply
      else
        echo "Terraform plan failed!"
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'

deploy_job:
  stage: deploy
  before_script:
    - cd frontend
  script:
    - echo $(pwd)
    - npm install
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'