stages:
  - infra

infra_job:
  stage: infra
  image: hashicorp/terraform:latest
  before_script:
    - cd infra/terraform
  script:
    - echo $(pwd)
    - terraform init
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'