stages:
  - infra
  - build
  - deploy

infra_job:
  stage: infra
  before_script:
    - cd infra/terraform
  script:
    - echo $(pwd)
    - gitlab-terraform init
    - gitlab-terraform plan
    - |
      if [ $? -eq 0 ]; then 
        gitlab-terraform apply
      else
        echo "Terraform plan failed!"
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

build_frontend:
  stage: build
  before_script:
    - cd frontend
  script:
    - echo $(pwd)
    - npm install
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  image: node:14-alpine

deploy_frontend:
  stage: deploy
  script:
    - aws s3 sync frontend/build/ s3://frontend-c3-equipo3
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  image: registry.gitlab.com/gitlab-org/aws-cli:latest