stages:
  - infra

infra_job:
  stage: infra
  image: hashicorp/terraform:1.0.0
  script:
    - cd infra/terraform && terraform init
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'