stages:
  - infra
  - build
  - test
  - deploy

infra_job:
  stage: infra
  before_script:
    - cd infra/terraform
  script:
    - echo $(pwd)
    - gitlab-terraform init
    - gitlab-terraform plan
    - |
      if [ $? -eq 0 ]; then 
        gitlab-terraform apply
      else
        echo "Terraform plan failed!"
      fi
  rules:
    - changes:
        - infra/terraform/**/*
      if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "feature/iac"'
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

build_frontend:
  stage: build
  before_script:
    - cd frontend
  script:
    - echo $(pwd)
    - npm install
    - npm run build
    - echo $(ls)
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  image: node:16-alpine
  artifacts:
    paths:
      - frontend/dist/

test_frontend:
  stage: test
  before_script:
    - cd frontend
  script:
    - echo $(pwd)
    - echo "Testing"
    - npm install
    - npm test
    - echo "Finished testing"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  image: node:16-alpine

deploy_frontend:
  stage: deploy
  needs:
    - build_frontend
    - test_frontend
  before_script:
    - cd frontend
  script:
    - echo $(pwd)
    - echo $(ls)
    - echo "Deploy frontend to S3 bucket"
    - aws s3 cp dist/ s3://frontend-c3-equipo3 --recursive
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  dependencies:
    - build_frontend

test_backend:
  stage: test
  before_script:
    - cd backend
  script:
    - echo $(pwd)
    - echo "Running tests ..."
    - bash ../generate_application_secrets.sh > ../application-secrets.properties
    - mvn test
  after_script:
    - cp ../application-secrets.properties $CI_PROJECT_DIR/application-secrets.properties
    artifacts:
      paths:
        - $CI_PROJECT_DIR/application-secrets.properties
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "feature/pipeline"'
  image: maven:latest

deploy_backend:
  stage: deploy
  needs:
    - test_backend
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" > private_key.pem
    - chmod 400 private_key.pem
  script:
    - echo $(pwd)
    - echo "Deploying started ..."
    - scp -i private_key.pem -o StrictHostKeyChecking=no -r backend Dockerfile ubuntu@$SERVER_IP:/home/ubuntu/
    - scp -i private_key.pem -o StrictHostKeyChecking=no $CI_PROJECT_DIR/application-secrets.properties ubuntu@3.141.149.37:/home/ubuntu/backend/src/main/resources/
    - echo $(ls)
    - ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@$SERVER_IP 'bash -s' < infra/scripts/instance_script.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "feature/pipeline"'
  image: ubuntu:mantic
