default:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

before_script:
  - cd infra/terraform

stages:
  - infra

infra_job:
  stage: infra
  script:
    - gitlab-terraform init
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'