default:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

before_script:
  - cd infra/terraform
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

stages:
  - infra

infra_job:
  stage: infra
  script:
    - echo $(pwd)
    - gitlab-terraform init
    - gitlab-terraform plan
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'